### ISSUE TITLE
Problem to build the project of fedora core 31

### ISSUE THREAD

**Issue by ezerbib** [h4tr3d/gdbproxy#1]
Hello I have some problem to build the project

gcc - 9.2.1
asio 1.10.8-10.fc31 
OS : fedora core 31

[ezerbib@localhost build]$ make
[ 8%] Building CXX object CMakeFiles/gdbproxy.dir/proxy-conn.cpp.o
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp: In member function ‘void connection::channel::start_write(std::shared_ptr<connection>, transfer&&)’:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: error: no matching function for call to ‘buffer(std::string_view)’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:706:26: note: candidate: ‘asio::mutable_buffers_1 asio::buffer(const asio::mutable_buffer&)’
  706 | inline mutable_buffers_1 buffer(const mutable_buffer& b)
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:706:55: note:   no known conversion for argument 1 from ‘std::string_view’ {aka ‘std::basic_string_view<char>’} to ‘const asio::mutable_buffer&’
  706 | inline mutable_buffers_1 buffer(const mutable_buffer& b)
      |                                 ~~~~~~~~~~~~~~~~~~~~~~^
/usr/include/asio/buffer.hpp:718:26: note: candidate: ‘asio::mutable_buffers_1 asio::buffer(const asio::mutable_buffer&, std::size_t)’
  718 | inline mutable_buffers_1 buffer(const mutable_buffer& b,
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:718:26: note:   candidate expects 2 arguments, 1 provided
/usr/include/asio/buffer.hpp:735:24: note: candidate: ‘asio::const_buffers_1 asio::buffer(const asio::const_buffer&)’
  735 | inline const_buffers_1 buffer(const const_buffer& b)
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:735:51: note:   no known conversion for argument 1 from ‘std::string_view’ {aka ‘std::basic_string_view<char>’} to ‘const asio::const_buffer&’
  735 | inline const_buffers_1 buffer(const const_buffer& b)
      |                               ~~~~~~~~~~~~~~~~~~~~^
/usr/include/asio/buffer.hpp:747:24: note: candidate: ‘asio::const_buffers_1 asio::buffer(const asio::const_buffer&, std::size_t)’
  747 | inline const_buffers_1 buffer(const const_buffer& b,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:747:24: note:   candidate expects 2 arguments, 1 provided
/usr/include/asio/buffer.hpp:764:26: note: candidate: ‘asio::mutable_buffers_1 asio::buffer(void*, std::size_t)’
  764 | inline mutable_buffers_1 buffer(void* data, std::size_t size_in_bytes)
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:764:26: note:   candidate expects 2 arguments, 1 provided
/usr/include/asio/buffer.hpp:773:24: note: candidate: ‘asio::const_buffers_1 asio::buffer(const void*, std::size_t)’
  773 | inline const_buffers_1 buffer(const void* data,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:773:24: note:   candidate expects 2 arguments, 1 provided
/usr/include/asio/buffer.hpp:787:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(PodType (&)[N])’
  787 | inline mutable_buffers_1 buffer(PodType (&data)[N])
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:787:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   mismatched types ‘PodType [N]’ and ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:800:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(PodType (&)[N], std::size_t)’
  800 | inline mutable_buffers_1 buffer(PodType (&data)[N],
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:800:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   mismatched types ‘PodType [N]’ and ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:817:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const PodType (&)[N])’
  817 | inline const_buffers_1 buffer(const PodType (&data)[N])
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:817:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   mismatched types ‘const PodType [N]’ and ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:830:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const PodType (&)[N], std::size_t)’
  830 | inline const_buffers_1 buffer(const PodType (&data)[N],
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:830:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   mismatched types ‘const PodType [N]’ and ‘std::string_view’ {aka ‘std::basic_string_view<char>’}
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:916:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(boost::array<PodType, N>&)’
  916 | inline mutable_buffers_1 buffer(boost::array<PodType, N>& data)
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:916:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘boost::array<PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:930:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(boost::array<PodType, N>&, std::size_t)’
  930 | inline mutable_buffers_1 buffer(boost::array<PodType, N>& data,
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:930:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘boost::array<PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:947:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(boost::array<const PodType, N>&)’
  947 | inline const_buffers_1 buffer(boost::array<const PodType, N>& data)
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:947:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘boost::array<const PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:961:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(boost::array<const PodType, N>&, std::size_t)’
  961 | inline const_buffers_1 buffer(boost::array<const PodType, N>& data,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:961:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘boost::array<const PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:980:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const boost::array<PodType, N>&)’
  980 | inline const_buffers_1 buffer(const boost::array<PodType, N>& data)
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:980:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const boost::array<PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:994:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const boost::array<PodType, N>&, std::size_t)’
  994 | inline const_buffers_1 buffer(const boost::array<PodType, N>& data,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:994:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const boost::array<PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1013:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(std::array<_Tp, _Nm>&)’
 1013 | inline mutable_buffers_1 buffer(std::array<PodType, N>& data)
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:1013:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::array<_Tp, _Nm>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1027:26: note: candidate: ‘template<class PodType, long unsigned int N> asio::mutable_buffers_1 asio::buffer(std::array<_Tp, _Nm>&, std::size_t)’
 1027 | inline mutable_buffers_1 buffer(std::array<PodType, N>& data,
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:1027:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::array<_Tp, _Nm>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1044:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(std::array<const PodType, N>&)’
 1044 | inline const_buffers_1 buffer(std::array<const PodType, N>& data)
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1044:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::array<const PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1058:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(std::array<const PodType, N>&, std::size_t)’
 1058 | inline const_buffers_1 buffer(std::array<const PodType, N>& data,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1058:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::array<const PodType, N>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1075:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const std::array<_Tp, _Nm>&)’
 1075 | inline const_buffers_1 buffer(const std::array<PodType, N>& data)
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1075:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::array<_Tp, _Nm>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1089:24: note: candidate: ‘template<class PodType, long unsigned int N> asio::const_buffers_1 asio::buffer(const std::array<_Tp, _Nm>&, std::size_t)’
 1089 | inline const_buffers_1 buffer(const std::array<PodType, N>& data,
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1089:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::array<_Tp, _Nm>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1111:26: note: candidate: ‘template<class PodType, class Allocator> asio::mutable_buffers_1 asio::buffer(std::vector<_Tp, _Alloc>&)’
 1111 | inline mutable_buffers_1 buffer(std::vector<PodType, Allocator>& data)
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:1111:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::vector<_Tp, _Alloc>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1134:26: note: candidate: ‘template<class PodType, class Allocator> asio::mutable_buffers_1 asio::buffer(std::vector<_Tp, _Alloc>&, std::size_t)’
 1134 | inline mutable_buffers_1 buffer(std::vector<PodType, Allocator>& data,
      |                          ^~~~~~
/usr/include/asio/buffer.hpp:1134:26: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘std::vector<_Tp, _Alloc>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1160:24: note: candidate: ‘template<class PodType, class Allocator> asio::const_buffers_1 asio::buffer(const std::vector<_Tp, _Alloc>&)’
 1160 | inline const_buffers_1 buffer(
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1160:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::vector<_Tp, _Alloc>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1184:24: note: candidate: ‘template<class PodType, class Allocator> asio::const_buffers_1 asio::buffer(const std::vector<_Tp, _Alloc>&, std::size_t)’
 1184 | inline const_buffers_1 buffer(
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1184:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::vector<_Tp, _Alloc>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1207:24: note: candidate: ‘template<class Elem, class Traits, class Allocator> asio::const_buffers_1 asio::buffer(const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>&)’
 1207 | inline const_buffers_1 buffer(
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1207:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
In file included from /usr/include/asio/detail/reactive_socket_service.hpp:22,
                 from /usr/include/asio/datagram_socket_service.hpp:30,
                 from /usr/include/asio/basic_datagram_socket.hpp:21,
                 from /usr/include/asio.hpp:19,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/common.h:3,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.hpp:5,
                 from /home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:1:
/usr/include/asio/buffer.hpp:1230:24: note: candidate: ‘template<class Elem, class Traits, class Allocator> asio::const_buffers_1 asio::buffer(const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>&, std::size_t)’
 1230 | inline const_buffers_1 buffer(
      |                        ^~~~~~
/usr/include/asio/buffer.hpp:1230:24: note:   template argument deduction/substitution failed:
/home/ezerbib/work/asio-gdbproxy/gdbproxy/proxy-conn.cpp:240:57: note:   ‘std::string_view’ {aka ‘std::basic_string_view<char>’} is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Allocator>’
  240 |     asio::async_write(m_dst, asio::buffer(pkt.raw_data()),
      |                                                         ^
make[2]: *** [CMakeFiles/gdbproxy.dir/build.make:89: CMakeFiles/gdbproxy.dir/proxy-conn.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/gdbproxy.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ezerbib** [comment]
It seam that my asio lib doesn't accept string_view in function asio::buffer

I found that replacing string_view by std::string  fix the compilation as following

std::string gdb_packet::raw_data() const noexcept
{
    return m_state == state::invalid ?
                std::string() :
                std::string(m_data.data(), m_data.size());
}
and in class definition
for gdb_packet
....
 std::string raw_data() const noexcept;

**Comment by h4tr3d** [comment]
Sorry for a long delay. Seems your Asio version too old. My own one is 1.14.0 and all work well.

**Comment by h4tr3d** [comment]
Try https://github.com/h4tr3d/gdbproxy/commit/1a537a10dd873f4a67bdb11fce88085bbabc22dd should solve issue.

**Comment by ezerbib** [comment]
thanks ok
